### PR TITLE
Update endless.go

### PR DESCRIPTION
**Pull request by dyxushuai**

### CODE REVIEW

**Comment by fvbock** [comment]
i am not sure i understand your question. the listener needs to get closed on the parent after forking so that the Accept function and finally Serve will return.

**Comment by dyxushuai** [comment]
Sorry, I mean that if we can just call `Close()` method directly. 

``` go
func newEndlessListener(l net.Listener, srv *endlessServer) (el *endlessListener) {
    return &endlessListener{
        Listener: l,
        stop:     make(chan error),
        server:   srv,
    }
}

func (el *endlessListener) Close() error {
    if el.stopped {
        return syscall.EINVAL
    }
    el.stopped = true
    return el.Listener.Close()
}
```

call `(*TCPListener).Close()` method without a `stop` channel.
I just can not understand this goroutine here

``` go
go func() {
    _ = <-el.stop
    el.stopped = true
    el.stop <- el.Listener.Close()
}()
```

If it has special significance?

**Comment by fvbock** [comment]
i remember that when i started putting things together from grishas ideas that part was the one that  confused me at first - but it was needed - _i think_ the parent just exited because there were no other goroutines running and did not serve outstanding requests... but i cannot remember exactly.
looking at it now it does not really make sense any more. probably lost it's meaning at some point when the whole thing came together using the same signatures as the stl ListenAndServe. my gutfeeling right now is that it can be removed... will have to write some tests... still an outstanding todo... i will look into it on the weekend and get back to you then.

**Comment by dyxushuai** [comment]
:) THX

**Comment by fvbock** [comment]
sorry - took a while...

https://github.com/fvbock/endless/tree/remove_channeled_close

here is a version that uses calls Close() directly. i added a very simple (hacky;) test script: `go run test/test_restarting.go` it relies on `ab` - apache bench. it makes 10000 requests to a test server (100 concurrent) which take random times between 1~1000ms while hitting the server with restart signals (`SIGHUP`). 

as a first test that looks all good:

```
Document Path:          /foo
Document Length:        4 bytes

Concurrency Level:      100
Time taken for tests:   94.275 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      1200000 bytes
HTML transferred:       40000 bytes
```

maybe you can help me test a bit more?  will then hopefully soon merge this into master.

**Comment by dyxushuai** [comment]
No problem, I will take the time to do this. But one or two days perhaps.

**Comment by fvbock** [comment]
merged the changes into master: https://github.com/fvbock/endless/pull/5

closing this

**Pull request closed without merging**
